// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-okhb7PFlVprJ51HGEhXvP1Z0Jqsx34',
    appId: '1:138281983284:web:c7e73b3322cac9ec95d961',
    messagingSenderId: '138281983284',
    projectId: 'purugging-auth-45d15',
    authDomain: 'purugging-auth-45d15.firebaseapp.com',
    storageBucket: 'purugging-auth-45d15.appspot.com',
    measurementId: 'G-7F3B6TJSWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA12psZU0dpwSYYqDhtRfdUEgOvSPQXDJU',
    appId: '1:138281983284:android:fc55b2ec3486b30c95d961',
    messagingSenderId: '138281983284',
    projectId: 'purugging-auth-45d15',
    storageBucket: 'purugging-auth-45d15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCvSbgA5aDEnjyVhOyCR8mfjQXiZ5ukUY',
    appId: '1:138281983284:ios:54360137475e283a95d961',
    messagingSenderId: '138281983284',
    projectId: 'purugging-auth-45d15',
    storageBucket: 'purugging-auth-45d15.appspot.com',
    iosBundleId: 'com.example.purugging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCvSbgA5aDEnjyVhOyCR8mfjQXiZ5ukUY',
    appId: '1:138281983284:ios:d3e3bb0163a2233595d961',
    messagingSenderId: '138281983284',
    projectId: 'purugging-auth-45d15',
    storageBucket: 'purugging-auth-45d15.appspot.com',
    iosBundleId: 'com.example.purugging.RunnerTests',
  );
}
